### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by hamswolo** [yuliskov/SmartTube#1764]
Just updated buffering every 2 seconds. No other steaming service has an issue and a speed  test is fine . Firestick 4k

**Comment by helloeverything1** [comment]
Same for me on nvidia shield. Lots of people have a very similar problem, I hope it gets fixed soon.

**Comment by KG3RK3N** [comment]
Same problem on my Odroid C2

**Comment by ChaliKaki** [comment]
me too..vontar box..
pity was perfect till yesterday..
thanks anyway

**Comment by pannal** [comment]
This is the third recent thread about this issue. At least see if you're duplicating before posting.

**Comment by BDaggerhart** [comment]
Same here, been happening for about 3 hours now (while not having problems this morning).

NVidia Shield

**Comment by meddle99** [comment]
Same issue here on a shield.  Tried clearing cache, uninstalling and rebooting with no improvement.  Commercials with original app are terribly annoying but everything plays fine.

**Comment by Zero6288** [comment]
This was driving me insane. >.< At least it's not just me.

**Comment by Gregz15** [comment]
Same problem, it seems it has to be with the account, if you log out the problem is not present at least for me, I have 2 android tv box and the problem is in both. uninstall and reinstall don't fix the problem I even tried with an older version but same problem.

**Comment by smoke63b** [comment]
Same problem. I have gigabit. ONN device on 5ghz. Can't even play 1080p at a 1.5mb rate. Freezes on black screen after selecting video. 5 to 10 seconds later, buffering. Plays 1 second, buffering. Sometimes it keeps doing this. Sometimes it just buffers infinitely. 

Fully updated. Didn't have this problem yesterday.

**Comment by neooblaster** [comment]
> Same problem, it seems it has to be with the account, if you log out the problem is not present at least for me, I have 2 android tv box and the problem is in both. uninstall and reinstall don't fix the problem I even tried with an older version but same problem.

Same issue. Without account, there is no buffering issue. Once connected, it's not possible to watch a video.
My opinion is Youtube put bandwidth restriction when we watch video with SmartubeNext.

Hope you will find the root cause.

Kindly regards.

**Comment by BirukTes** [comment]
> 

I also suspect that YT maybe tweaking parameters? But do not know for sure.

**Comment by mcrypt** [comment]
Yap.. same problem here! Buffer hell :-(

**Comment by TA3** [comment]
> > Same problem, it seems it has to be with the account, if you log out the problem is not present at least for me, I have 2 android tv box and the problem is in both. uninstall and reinstall don't fix the problem I even tried with an older version but same problem.
> 
> Same issue. Without account, there is no buffering issue. Once connected, it's not possible to watch a video. My opinion is Youtube put bandwidth restriction when we watch video with SmartubeNext.
> 
> The problem appears only few hour ago. (5/10 hours max)
> 
> Hope you will find the root cause.
> 
> Kindly regards.

Same exact issue here.

**Comment by ShamelessWizard** [comment]
I installed stable, logged in and I'm not seeing buffering. Beta is buffering on both televisions. Is everyone else using Beta?

**Comment by neooblaster** [comment]
> > 
> 
> I also suspect that YT maybe tweaking parameters? But do not know for sure.

Today, I got an security alert from my Gmail account. "A user knows the password for your associated Google Account"
I change my password, but I don't find anything about settings in Youtube that can be reset.

Anyone got a security alert ?

**Comment by ShamelessWizard** [comment]
> > > 
> > 
> > 
> > I also suspect that YT maybe tweaking parameters? But do not know for sure.
> 
> Today, I got an security alert from my Gmail account. "A user knows the password for your associated Google Account" I change my password, but I don't find anything about settings in Youtube that can be reset.
> 
> Anyone got a security alert ?

Nope!

**Comment by waynezo** [comment]
Same here on both Firestick 4k max and Firestick 4k

**Comment by mystreamhub** [comment]
sign out fix the problem

**Comment by nckfrs** [comment]
Sign out to fix the issue for now not sure why but it works

**Comment by BirukTes** [comment]
> sign out fix the problem



> Sign out to fix the issue for now not sure why but it works

You can just select the “None” from the accounts selection.

**Comment by Shinobyte** [comment]
Same issue here, on a Nvidia Shield

**Comment by 1992ff** [comment]
Same problem for me with my fire tv stick 4k on Beta version 15.76. A few hours ago everything was fine. The official YouTube app hasn't this buffering issues at the moment...

**Comment by wilsoncliu** [comment]
They just came out with 15.78, and that fixed it for me.

**Comment by ypk** [comment]
OMG I was thinking I was the only one with this issue!

**Comment by amahi2001** [comment]
Same issue here on Nvidia shield. My wifi speed is still the same as it was before and other streaming services seem to work.

**Comment by Coollius** [comment]
Can confirm, the issue is fixed in latest beta 15.78

**Comment by BDaggerhart** [comment]
Works with latest update, 15.78

Nvidia Shield

Thanks!

**Comment by Stryder24** [comment]
Just updated to 15.78 on my Firestick And m videos will not play.  First a black screen comes up, and then it goes back to my subscriptions page

**Comment by Dom51487** [comment]
Guys I am kind of a newbie and may have installed the APK file from SmartTubeNext.com the website says its official but im worried I may have downloaded Malware onto my TV can anyone confirm if this website is legit or not I'm sorry

**Comment by psx123** [comment]
> 

Uninstall that APK and download it from GitHub. Scan Kaspersky antivirus

**Comment by ypk** [comment]
> Uninstall that APK and download it from GitHub. Scan Kaspersky antivirus

You don't actually need to. You can update the app directly from Settings > About inside the app

**Comment by psx123** [comment]
> > Uninstall that APK and download it from GitHub. Scan Kaspersky antivirus
> 
> You don't actually need to. You can update the app directly from Settings > About inside the app

They have download the APK from a random source?

**Comment by ypk** [comment]
> OMG I was thinking I was the only one with this issue!

I updated to 15.78 and everything works like expected :)

**Comment by ypk** [comment]
> > > Uninstall that APK and download it from GitHub. Scan Kaspersky antivirus
> > 
> > 
> > You don't actually need to. You can update the app directly from Settings > About inside the app
> 
> They have download the APK from a random source?

I didn't read the comment earlier, I've updated my original reply

**Comment by Dom51487** [comment]
> Kaspersky antivirus

Ok just to make sure I'm clear I downloaded APK from that website for my Android TV. Is it still worth running an antivirus?

**Comment by psx123** [comment]
> > Kaspersky antivirus
> 
> Ok just to make sure I'm clear I downloaded APK from that website for my Android TV. Is it still worth running an antivirus?

Yes download it from this GitHub and run the antivirus

**Comment by Dom51487** [comment]
> Kaspersky

I have to download the antivirus from an APK website because I cant find any in the Google Play TV store

**Comment by psx123** [comment]
> > Kaspersky
> 
> I have to download the antivirus from an APK website because I cant find any in the Google Play TV store

Scan, once nothing is found then uninstall the antivirus

**Comment by Dom51487** [comment]
> > > Kaspersky
> > 
> > 
> > I have to download the antivirus from an APK website because I cant find any in the Google Play TV store
> 
> Scan, once nothing is found then uninstall the antivirus

Ok thank you so much

**Comment by hxd2772** [comment]
Everyone, the problem is fixed in 15.79!

**Comment by neooblaster** [comment]
I confirm the issue is fixed with retrieve version from "about" menu (15.78).

Thanks a lot for the support

**Comment by omsharp** [comment]
The issue is solved with 15.78 update.

**Comment by RyuFTH** [comment]
Fire stick TV, since yesterday i hibe to turn down the video quality in order to watch anything uninterrupted. YouTube official app working perfectly, and i can watch streams on twitch without a problem too.

 Tried reinstalling but the issue persists. Hope it gets patched soon, i use this app daily.

**Comment by ACR-Jeff** [comment]
Bad buffering on Waydroid, No newer versions will install.

**Comment by Chealer** [comment]
@hamswolo : Which version do you use? And how does this differ from issue #1762?
