### ISSUE TITLE
While watching playback queue, pressing the skip button deletes remaining queued videos

### ISSUE THREAD

**Issue by amphoterism** [yuliskov/SmartTube#2498]
Just like the title says, if you have a queue of videos and you skip one by pressing the skip button, it will go to a new video, but the rest of the queued videos will be deleted, rather than going to the next video in the queue.

**Comment by kliao93** [comment]
Also having this issue since about a week ago, seems to be the only bug I've noticed since installing a half year ago and not accompanied by any other weird behavior

**Comment by MikeTheDead** [comment]
Same issue, I didnt connect the skip button with this behavior because i do it without thinking. Hoping this is fixed soon

**Comment by amphoterism** [comment]
I've noticed it also happens even without skipping. Perhaps it has to do
with the playback queue being full? Is there a way to clear the playback
queue?

**Comment by MikeTheDead** [comment]
Not that ive been able to see except individually removing them, i just reset the app

**Comment by kamilkrz** [comment]
On small queue the problem still occurs and is present since ~2-3 weeks so the point is still valid.
