### ISSUE TITLE
[BUG]: Playlists not opening

### ISSUE THREAD

**Issue by gigs96** [yuliskov/SmartTube#3977]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.14

### Device Type

Smart TV/Box

### Affected Android

Android TV 11

### Steps to reproduce the bug

1. Go to Library section. 
2. Open any playlist that isn't "Watch later."

### Actual behavior

With the exception of "Watch later", none of my playlists are loading. Whenever i try opening one, it just stays in a black screen. Also, trying to access a playlist via lateral bar redirects me to the error screen. This has been happening since yesterday, i tried restarting my internet, my TV, resetting the app data but nothing fixed it.

**Comment by kaolincash** [comment]
I would like to confirm I also have this issue, as described, on my Nvidia Shield (also on Android 11); I noticed it shortly after midnight last night.

I have confirmed my app is updated to the latest version (24.14).

When playlists are shown as a grid, none except Watch Later and My Videos will load when selected (i.e. no custom playlists made by me or others will load, only YouTube's default playlists function as normal). 

When playlists are shown in rows, only Watch Later and My Videos appear as options--no custom playlists made by me or others will appear at all.

**Comment by Ruslana-Kara** [comment]
I would like to confirm what was written in previous comments. Also on Android 11 and TVBox. Tried different versions.

**Comment by nitinjs** [comment]
I re-added the same google account in `Settings->Accounts` and it worked like a charm

**Comment by pinkfloydhomer** [comment]
> I re-added the same google account in `Settings->Accounts` and it worked like a charm

I cleared storage and started from scratch, problem still exists.

**Comment by KevinNovak** [comment]
+1, I'm also running into this issue. 

Clearing cache and storage and logging in again did not fix

**Comment by nitinjs** [comment]
I mean to say `Settings->Accounts->Sign In`

**Comment by pinkfloydhomer** [comment]
Doesn't help

**Comment by dberthia** [comment]
Issue confirmed on my Nvidia Shield.

**Comment by 420-420** [comment]
same here firestick 4k. thanks

**Comment by RBGiant** [comment]
Same on chromecast 4k. Worked until it didn't. Also it still works on my gfs account.

**Comment by nulk1** [comment]
Exact same issue on my Chromecast 4K w/Google TV

**Comment by dstein766** [comment]
+1.  Chromecast 4k.  Began following an update (roughly) 5-6 days ago and has persisted.

**Comment by rmarsack** [comment]
I have ONN 4k Android devices and have the same issue, thank you.

**Comment by FutureHistory** [comment]
Having the exac5 same issue here. Running stube on firestick

**Comment by dstein766** [comment]
Confirming that this appears to have been fixed in beta 24.25, as per release note.  Thank you!

**Comment by KevinNovak** [comment]
Fixed for me as well in the latest beta release, thank you!

**Comment by Juddda65** [comment]
The 24.25 beta release has fixed this issue on my three devices as well, thankyou for your support 👍

**Comment by FutureHistory** [comment]
Not fixed for me yet on 24.4. do I need to download something onto my firestick?

**Comment by kaolincash** [comment]
I still have the issue on 24.26 beta

**Comment by fish7yu** [comment]
I am encountering the same issue.

Currently running stable verion 24.14 on Mi Box S Gen 2.

**Comment by apk491** [comment]
I am experiencing same on Nvidia Shield Pro, running stable 24.14. First noticed ~2 days ago but have been away from home for a week so unsure when it begun. 

Playlists section correctly displays playlists. Upon opening it returns entirely blank black screen. 

I have a couple of my personal playlists pinned to sidebar. When selecting from SB it displays the sign in prompt despite being signed in. Attempted re-sign in with same results. 

Can manage playlist content by holding on video and add or remove from playlists in context menu. 

'Watch Later' and History still work and seemingly no loss of any other features.

**Comment by RBGiant** [comment]
Works for me after switching to beta on chromecast 4k w/ Google Tv.
Thanks!

**Comment by kaolincash** [comment]
Playlists now work on Nvidia Shield beta 24.38, but not on stable 24.37

**Comment by roddersGB** [comment]
Since the 25.81 update playlists have stopped working on my Nvidia Shield Pro.  Playlists are displayed but selecting any of them causes a slight flicker of the icon then nothing.
