### ISSUE TITLE
[BUG]: black screen doesn't play 

### ISSUE THREAD

**Issue by allnamesaretakennow** [yuliskov/SmartTube#4181]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.89

### Device Type

Smart TV/Box

### Affected Android

Android tv 12

### Steps to reproduce the bug

Can't start any video, screen is just black. 

### Actual behavior

When I press play the screen is just black. 

### Additional information

It's on a Nokia tv box. 

The problem occured yesterday when it stopped working. 

It has been working before fine so it's not the problem of the box.

**Comment by astraetech** [comment]
Same problem, latest gen 4k max firestick with updated logged-in smarttube and fireos. Videos don't play just the OSD appears and pressing play doesn't do anything. Restarting firestick did not help.

**Comment by brhv098** [comment]
Same happened to me too on my G1 tv box

**Comment by Keiyuu** [comment]
Same here on Sony Android TV. Can't watch any videos, just black screen.

**Comment by bubuleur** [comment]
Same problem here on an Nvidia Shield TV Pro I emptied the cache stopped the application and I put on the latest beta version it still doesn't work impossible to play any video 
Thnaks

**Comment by khan-belal** [comment]
Same issue on my Sony TV using v25.01.

Infinite black loading screen when attempting to play videos

**Comment by j3lte** [comment]
Same issue on my Nvidia Shield. This `logcat` might be useful (don't know for sure):

```log
12-06 17:38:40.089 15797 15870 W System.err: java.lang.IllegalStateException: NSigExtractor: Can't obtain NSig code for https://www.youtube.com/s/player/3bb1f723/tv-player-es6.vflset/tv-player-es6.js...
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.app.nsig.NSigExtractor.<init>(NSigExtractor.kt:63)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.app.AppService.updatePlayerData(AppService.java:350)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.app.AppService.getClientPlaybackNonceFunction(AppService.java:297)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.app.AppService.getClientPlaybackNonce(AppService.java:150)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoApiHelper.createCheckedQuery(VideoInfoApiHelper.java:64)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoApiHelper.createCheckedQuery(VideoInfoApiHelper.java:60)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoApiHelper.getVideoInfoQuery(VideoInfoApiHelper.java:36)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoService.getVideoInfo(VideoInfoService.java:192)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoService.getVideoInfo(VideoInfoService.java:133)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoService.getRootVideoInfo(VideoInfoService.java:116)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.videoinfo.V2.VideoInfoService.getVideoInfo(VideoInfoService.java:62)
12-06 17:38:40.093 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.service.YouTubeMediaItemService.getFormatInfo(YouTubeMediaItemService.java:85)
12-06 17:38:40.094 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.service.YouTubeMediaItemService.getFormatInfo(YouTubeMediaItemService.java:74)
12-06 17:38:40.094 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.service.YouTubeMediaItemService.lambda$getFormatInfoObserve$1$YouTubeMediaItemService(YouTubeMediaItemService.java:101)
12-06 17:38:40.094 15797 15870 W System.err: 	at com.liskovsoft.youtubeapi.service.-$$Lambda$YouTubeMediaItemService$HynjQsP9RJphTinqqpFAiqdV5tA.call(Unknown Source:4)
12-06 17:38:40.094 15797 15870 W System.err: 	at com.liskovsoft.sharedutils.rx.RxHelper.lambda$fromNullable$13(RxHelper.java:249)
12-06 17:38:40.094 15797 15870 W System.err: 	at com.liskovsoft.sharedutils.rx.-$$Lambda$RxHelper$iC1Gyv_JFKl5A2iXhGyPMp4GAVk.subscribe(Unknown Source:2)
12-06 17:38:40.094 15797 15870 W System.err: 	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
12-06 17:38:40.094 15797 15870 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12284)
12-06 17:38:40.094 15797 15870 W System.err: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-06 17:38:40.094 15797 15870 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
12-06 17:38:40.094 15797 15870 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-06 17:38:40.094 15797 15870 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-06 17:38:40.094 15797 15870 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-06 17:38:40.094 15797 15870 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-06 17:38:40.094 15797 15870 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-06 17:38:40.094 15797 15870 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-06 17:38:40.094 15797 15870 W System.err: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by bubuleur** [comment]
Now it's back with version 24.89 the video works again, I don't know where it could come from

**Comment by RomanoR18** [comment]
Not working for me now as well. I have the latest update

**Comment by V4ler1an** [comment]
> Now it's back with version 24.89 the video works again, I don't know why did it go wrong

That version doesn't work for me. It's the one i've been on since it stopped working yesterday. Could it be that updating fixed it for you?

**Comment by clienthax** [comment]
started working for me too without updating

**Comment by V4ler1an** [comment]
> started working for me too without updating

No dice here still. Some kind of regional issue / blocking maybe?

**Comment by bubuleur** [comment]
> > Now it's back with version 24.89 the video works again, I don't know why did it go wrong
> 
> That version doesn't work for me. It's the one i've been on since it stopped working yesterday. Could it be that updating fixed it for you?

No I don't think the beta version I installed and uninstalled right after and changed something 
I think it's regional it depends where you are located

**Comment by j3lte** [comment]
Somehow it started working for me again (Europe, Netherlands), using SmartTube Beta 25.02. This one had the black screen issue the whole day. The release version (SmartTube 24.89) didn't have issues.

**Comment by dberthia** [comment]
I'm in the US on the release version, and continue to see the issue. Usually if I wait for the spinner long enough (like 5 minutes), the video will play eventually.

**Comment by dberthia** [comment]
I'm in the US on the release version, and continue to see the issue. Usually if I wait for the spinner long enough (like 5 minutes), the video will play eventually.

**Comment by mcrypt** [comment]
In Europe on a shield pro same issue

**Comment by flashground** [comment]
US. Somehow it started working for me. I didn't do anything.

**Comment by miroan81** [comment]
Europe, 24.89 version, no updates available. Black screen since yesterday

**Comment by wieli99** [comment]
Guest mode does not work here. 24.89 - Central Europe

**Comment by V4ler1an** [comment]
When I log out of my YT account, I can play videos. Log back in, black screen again. Account related again it seems?

**Comment by IndefiniteBen** [comment]
Fixed for me in the latest beta

**Comment by Conundroy** [comment]
I found a fix on 24.89, just force stop and clear cache and playback should work again for signed in sessions. Hope this works for you.

**Comment by Conundroy** [comment]
I found a fix on 24.89, just force stop and clear cache and playback should work again for signed in sessions. Hope this works for you.

**Comment by dberthia** [comment]
Force Stop and Clear Cache on 24.89 did NOT help in my case (US- Nvidia Shield Pro 2019)

**Comment by henrylai** [comment]
Google Chromecast HD here. On 24.89
Force stop and clear cache did not work.
I suspect this is some type of blocking on Google's end...

**Comment by apgeshev** [comment]
Fixes by
1. Force stopping the app
2. Clear cache data
3. Clear app data

Afterwards, I had to login again into my Google account and everything was working as expected

**Comment by aamkoivu** [comment]
I had same problem on Sony TV, got it working on latest stable version by changing setting:

Settings -> video player -> developer settings -> check use IPv4 DNS

(Or something similar, menu naming might a little bit differently due to translation from finnish.)

**Comment by V4ler1an** [comment]
> I had same problem on Sony TV, got it working on latest stable version by changing setting:
> 
> Settings -> video player -> developer settings -> check use IPv4 DNS
> 
> (Or something similar, menu naming might a little bit differently due to translation from finnish.)

The DNS setting didn't work for me. This did:

- Log out
- Force stop
- Clear Cache
- Re-authorise account

**Comment by V4ler1an** [comment]
> Fixed by
> 
>     1. Force stopping the app
> 
>     2. Clear cache data
> 
>     3. Clear app data
> 
> 
> Afterwards, I had to login again into my Google account and everything was working as expected

This is the solution (for 24.89 on a Shield TV Pro at least).

**Comment by aamkoivu** [comment]
> > I had same problem on Sony TV, got it working on latest stable version by changing setting:
> > Settings -> video player -> developer settings -> check use IPv4 DNS
> > (Or something similar, menu naming might a little bit differently due to translation from finnish.)
> 
> The DNS setting didn't work for me. This did:
> 
>     * Log out
> 
>     * Force stop
> 
>     * Clear Cache
> 
>     * Re-authorise account

I actually was using latest beta version, which stopped working. Tried clearing cache, which didn't help. Then installed the stable version logged in and it had the same problem and after that tried different settings. So fixing it seems a bit random, or at least somehow different for others. So it's an option to try if the wiping chache-thing doesn't help.

_Pure speculation: Maybe it's something on the server side and depends on what server you're connected and relogging connects you to random server (or random inside some area) and that's why the ipv4 fixed it for me. 
Actually server selection probably isn't actually random, but depends on load._

**Comment by davidakachaos** [comment]
25.03 Works here again, Europe, NL

**Comment by henrylai** [comment]
> Google Chromecast HD here. On 24.89 Force stop and clear cache did not work. I suspect this is some type of blocking on Google's end...

Update: didn't do anything, but it's fixed now

**Comment by dberthia** [comment]
What fixed it for me was routing SmartTube app traffic through my VPN. Disabling the VPN re-introduced the problem. My ISP in the US is Xfinity.

**Comment by V4ler1an** [comment]
> What fixed it for me was routing SmartTube app traffic through my VPN. Disabling the VPN re-introduced the problem. My ISP in the US is Xfinity.

My whole network is on a vpn, I still had the issue until I cleared the cache. Changed servers, changed countries, tried bypassing the VPN. Nothing worked. Before clearing the cache, what DID work, was logging my YT account out of the app. I could fix and recreated the problem back and forth just by logging out and back in. I believe the issue was something account related that was stored in the cache. So both logging out or clearing the cache resolved it for me. This also is the second time in recent memory that logging out my account has resolved an issue. Seems to be something to check early on.

**Comment by SorakaMafaka** [comment]
Same issue started happening today, version 25.04. 
Force close/clear cache/reinstall doesn't solve the issue.
UK, no VPN.

**Comment by V4ler1an** [comment]
> Same issue started happening today, version 25.04. Force close/clear cache/reinstall doesn't solve the issue. UK, no VPN.

There are two options, 'clear cache' but also above it 'clear data' (which also clears the cache). I used clear data after a force stop and it worked for me.

**Comment by SorakaMafaka** [comment]
> > Same issue started happening today, version 25.04. Force close/clear cache/reinstall doesn't solve the issue. UK, no VPN.
> 
> There are two options, 'clear cache' but also above it 'clear data' (which also clears the cache). I used clear data after a force stop and it worked for me.

Thanks, I've tried clear data and signing back in as well, no joy I'm afraid.

**Comment by V4ler1an** [comment]
> > > Same issue started happening today, version 25.04. Force close/clear cache/reinstall doesn't solve the issue. UK, no VPN.
> > 
> > 
> > There are two options, 'clear cache' but also above it 'clear data' (which also clears the cache). I used clear data after a force stop and it worked for me.
> 
> Thanks, I've tried clear data and signing back in as well, no joy I'm afraid.

I'm curious to know if this is an app bug or something Google is up to trying to block the client once it can identify them. My guess is the latter. If you have a VPN try it along with the data clear. If you're on fibre, reboot your router to get a new IP.

**Comment by TonyHoyle** [comment]
It was working this morning... this afternoon dead.  Even tried a full uninstall and reinstall, no dice.  Since the version hadn't changed from this morning I expect it's something that google has changed at their end.

**Comment by Phantomx2** [comment]
Was working yesterday, not this morning.
Rest cache and everything didn't help.
24.89 on shield tv pro, from Canada

**Comment by mcrypt** [comment]
Started working last night, now completly dead again.

**Comment by farpinellc** [comment]
all black here

**Comment by TheColdOne** [comment]
This just started happening for me within the last hour (was fine earlier this morning).

**Comment by gcogger** [comment]
Same for me, just started in the last hour. Never had the issue before.
This is using the original 'Chromecast with Google TV' (or whatever it's called!).

**Comment by vilm725** [comment]
Same for me, v24.89 on mi tv 3 (mssp3). Yesterday, everythink work fine but today, no way ... Do you think Google or the application is blocking it?

**Comment by susloparovdenis** [comment]
"clear data" didn't help in my case

**Comment by vmail** [comment]
reboot, force close, clear cache, signout/signin did not work, using the stable version, native android TV app works ok.
rebooting the the router to get a new IP after all of the above worked now

**Comment by jgawarecki** [comment]
I'm on v24.89, the network seems very finicky, sometimes the list of videos will load but not always.   I'm having trouble signing back in. I haven't been able to get any videos to load.  
I've tried to 
Force stop 
clear cache
Clear data
Check ipv4 box in setting  -> player --> developer 
Reset router

All to no avail.  I love this app, please fix it nerds!

**Comment by V4ler1an** [comment]
> reboot, force close, clear cache, signout/signin did not work, using the stable version, native android TV app works ok. rebooting the the router to get a new IP after all of the above worked now

Knew it ! Change of IP needed as well.

**Comment by gcogger** [comment]
I tried switching to a fixed IP address, so it's different from before, but to no avail.

**Comment by jgawarecki** [comment]
> Knew it ! Change of IP needed as well.

 You seem to have a grip on the problem since you could recreate it.  Do you think there is a proper order to do things?  Maybe i need to log out, clear cache, switch up ip address (by rebooting router for 10+ seconds) and then logging back in.. got any idea what to try?

**Comment by jgawarecki** [comment]
Above steps didn't work for me.  I'm out of ideas, sitting on my hands now till someone else has a bright idea.

**Comment by bubuleur** [comment]
the problem is back the videos no longer work 
YouTube wants SmartTube's skin

**Comment by jgawarecki** [comment]
Thanks for all the advice, I've tried it all now in multiple ways and it's still not working.  On the bright side my phone app (NewPipe) still works so the problem must have a solution right?

**Comment by sgh2415** [comment]
Same here. Firestick and tried all the fixes others mentioned

**Comment by Vindtr** [comment]
Just loaded my sony bravia. Worked fine this morning, but by the evening- same black screen everyone is reporting. I even installed the update the smarttube app provided

**Comment by dberthia** [comment]
New 25.08 stable fixes the issue
