### ISSUE TITLE
[BUG]: video stops playing [Sign in to confirm you're not a bot - This helps protect our community. Lear more]

### ISSUE THREAD

**Issue by Havor123** [yuliskov/SmartTube#4815]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.

### Affected version

Updated to 29.03, did not fix. 

### Device Type

Smart TV/Box

### Affected Android

11 (fully updated Shield) 

### Steps to reproduce the bug

When playing video, I get msg to sign in, and after seconds it skips to next video, and I get same msg, keeps skipping till stoped. 

From faq: Your IP address range might be temporaily/permanently blocked by YouTube from watching videos if you not signed in to your account.
- I am signed in. - 

### Additional information

Tried restarting app and divice.

**Comment by Dr-Jebus** [comment]
Getting the same issue. Oddly, signing out lets me watch videos again. I'm using the most recent Beta version.
(Edit)
Trying to reactivate and sign in again doesn't fix the issue.

**Comment by monoamin** [comment]
Might have been a temporary API quirk on YT's side. I was affected too this morning, but at the moment everything seems to be working again.

v28.78 on generic Android TV OS 14

Edit1: Fwiw, I have both a fixed ipv4 and ipv6 and am not using a VPN.

Edit2: It's coming and going, no noticeable pattern

Edit3: The beta works for me without this issue so far

**Comment by shen9175** [comment]
> Might have been a temporary API quirk on YT's side. I was affected too this morning, but at the moment everything seems to be working again.
> 
> v28.78 on generic Android TV OS 14

I still experience this "sign in not bot" issue. It seems google enforces the detction on third party youtube tools. Like yt-dlp also experiences the "sign in not bot" issue. They cannot resolve it. Only change IP can skip it.

**Comment by LoonyBeLuna** [comment]
I just watched like 3-5 videos and now I also get it at every video. After 3 seconds does it jump to the next video just to show the same 

Overview:
![Image](https://github.com/user-attachments/assets/ce91bd46-25d8-4c63-a489-444b628a824a)

Opening the video:

![Image](https://github.com/user-attachments/assets/27591d0e-3ce0-4c81-b09f-1b1b84a6e086)

DeepL translated:

![Image](https://github.com/user-attachments/assets/c4778e56-74c5-41d5-868a-bfee5911067d)

I am logged in, I even went to the settings and clicked again on "login" and it said success.

**Comment by widiot1** [comment]
Same issue. Some videos playing fine, but 90% of them give me the same message.

Edit. There is no reliable way for me to replicate. Sometimes videos work, more often than not the same videos don't work. Signing out and back in hasn't made a difference

**Comment by edfaro7** [comment]
Just bumping this as I'm experiencing the same. Started working fine again for a few videos, then the sign-in message came back. Tried logging out/logging back in

**Comment by raven428** [comment]
I got today morning absolutely same issue:
> Sign in to confirm you're not a bot - This helps protect our community

TLDR; try to authorize the original YouTube app with the same account and device, run some videos from subscriptions from there, and switch back to SmartTube. Some observations next

I have two separate Google accounts both never paid. First, for the living room, I subscribed to a visually spectacular channels, which is nice to see on a huge flat screen. Second, a home office room with a small screen mostly for talking content like interviews, podcasts, news, and so on. The first account is in use for about 30-40-50 minutes once or twice per day, mostly when I'm having a meal 🙄 The second is in use for about 14-16 hours per day while I'm at job

I woke up in the morning as usual, and while I was taking my breakfast today, I didn't run SmartTube on the first account. That's because I left a small part of the movie from the evening and preferred to finish watching it today. I proceeded to the office room, started SmartTube with the second account, and got this error instead of starting BBC news

I backed up my current version 28.78 of SmartTube and tried to upgrade SmartTube to the recent beta, downgrade to the 28.66 with no result. Then I walked to the living room with the first account and tried to start some video there, and the playback was started! The consequence is Google started blocks only highly active accounts on third-party players

I already had the original YouTube app 5.22.302 on the TV box device at the home office installed before from APK. So I started it, performed login through the `yt.be/activate` address, and ran a recent video from my subscriptions I left yesterday. Of course, it started successfully. With unskippable advertisements and the inability to increase the playback speed 😬

I decided to try my luck with switching to SmartTube, starting the same video, and it started with no issue!

**Comment by antonborodko** [comment]
I created a new google account and everything worked.

**Comment by skrivskithar** [comment]
these workarounds don't work for me, it's clearly youtube that's finding ways to block these apps

**Comment by LoonyBeLuna** [comment]
The bug is for me no longer happening.

**Comment by skrivskithar** [comment]
Tried with another account. Worked for a few hours, now back again to the same issue

Edit: saw there was an update. Seems fixed

**Comment by Figim** [comment]
**All yt playback error fix examples** 


**Playback can be spoofed. This is fixed by transferring to Vistordata. The same visitordata is transmitted for all clients.** VPN is blocked by youtube and should not be used 

https://github.com/TeamNewPipe/NewPipeExtractor/pull/1272
https://github.com/TeamNewPipe/NewPipeExtractor/pull/1297

**Potoken fixes http 403(source error) error (some clients)**

You should know that all web clients use po_token generated on the web. android vr client does not require cookies and potoken. Some clients do not support cookies 

Releated issue

https://github.com/yuliskov/SmartTube/issues/4695


**About SABR** 

YT has already prepared the SABR playback protocol 
There are fixes for this too. 


YTdlp pr; yt-dlp/yt-dlp#13515 Other: etwoo/youtube-unthrottle@76b48d0

Freetube: FreeTubeApp/FreeTube#7145

**About Clients**  

https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide

**Comment by miru299** [comment]
I started having this issue today, it keeps showing the msg to sign in, I tried clearing the cache and data for the app. 

Note: On the latest version of the app

**Comment by ounrequitedo** [comment]
> **All yt playback error fix examples**

So you're saying that smarttube needs to implement sabr to get around these buffering issues?

**Comment by Figim** [comment]
> > **All yt playback error fix examples**
> 
> So you're saying that smarttube needs to implement sabr to get around these buffering issues?

Yes.

**Comment by MarOnic12345** [comment]
This just started happening to me today. I'm on the latest beta version of the app, and signing out and signing back in does not fix it. And as others have stated, it only seems to happen on certain videos.

**Comment by Xmetalfanx** [comment]
having kept the stable version updated (and also having the beta version installed) i had both working but on the latest stable version JUST today (i see posts from awhile back ... at least a few days but everything was working here for me then) 

it also shows my account seems to be logged in and my subs and history, and all of that shows fine.... version 29.37 by the way

I JUST tried the beta verison and it's doing the same thing

**Comment by Xmetalfanx** [comment]
sorry for making another post but i cant seem to edit my last one ...anyway i tried like an hour or so after i made that post randomly and both versions worked ...i didn't do anything really ... no logut and login on the app... i didn't clear app data or cache ... I cant explain it but I did see the problem, here

**Comment by DavDaddy** [comment]
Anyone ever find a fix for this?  I just updated to the latest version from the potential compromised one and started getting this?

**Comment by LoonyBeLuna** [comment]
> Anyone ever find a fix for this? I just updated to the latest version from the potential compromised one and started getting this?

I'm on the newest version and I never had it again. Maybe you reinstall your app? Or make sure you are correct logged in.
I'm watching right now YouTube without issues.

**Comment by Spatchy** [comment]
Hey everyone, to keep the conversation about this issue in one place, can all further discussion please happen on #4287
